# Username
[username]
format = "[╭─$user](cyan)"
show_always = true

# Hostname
[hostname]
format = "[@](white)[$hostname](blue): "
ssh_only = false

# Directory
[directory]
style = "cyan"

# Duration
[cmd_duration]
format = "[$duration](dimmed white)"

# Time
[time]
format = "[│](cyan) [$time](dimmed white)\n"
time_format = "%r"
disabled = false

# Prompt
[character]
success_symbol = "[╰─>](cyan)"
error_symbol = "[╰─X](red)"
